language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_script:
  - "npm install -g mocha"
script:
  - "npm test"
notifications:
  email:
    on_success: never
    on_failure: always